
compile:
	hugo

listen:
	hugo server --watch

scp:
	scp -prq public/. zhan527@viterbi-scf1.usc.edu:~/public_html/

cv:
	cp ~/Desktop/USC/Documents/Curriculum\ Vitae/cv/out/ChiZhang_CV.pdf ./content/cv/